### ISSUE TITLE
Click Bait Stream Title Suggestions

### ISSUE THREAD

**Issue by w3cj** [CodingGarden/landscaping#23]
Add a suggestion for a click bait title to use on the channel below.

**Comment by derkarol** [comment]
Banana-style web scraping. With yellow click-bite banana on thumbnail scarped by the girl?. Unfortunatly that is ow YouTube works now.

**Comment by satyaneo** [comment]
Learn React in 30 mins
Learn making something like project

**Comment by RunnerV** [comment]
Hacking a DATABASE!!! Come Watch Me Crack The Code!

**Comment by drding00** [comment]
"The Way You're Typing Could Kill You..."
"Doing it in the Backend the Right Way."
"Scraping the Dark Web."
"10 Reasons Your Code Sucks."
"Boob Coding Boob Garden Boob Boob Kata"

**Comment by ronaldaug** [comment]
"How CJ earn money from coding"
"Building a full stack decentralized voting application with Gatsby, React, Node, Express, MongoDB, Apollo GraphQL API" ( I guess this includes many popular keywords 😂)
"Coding a javascript bot that can write javascript"

( Make sure to collaborate with a beautiful female programmer and add her pic in the video thumbnail 😹😹)
