### ISSUE TITLE
Update the template to support Twitch Subs

### ISSUE THREAD

**Issue by ivoencarnacao** [CodingGarden/landscaping#29]
Your idea may have already been suggested! Please search on the [issues tracker](https://github.com/CodingGarden/landscaping/issues) before creating a new one.

>NOTE: Please give your issue a descriptive title so it is easy to identify at a glance.

## (REQUIRED) What category does this issue fit into?

>Please limit your issue to 1 category.

* [ ] App Idea
* [ ] App Constraint
* [ ] Front-end Technology
* [ ] Back-end Technology
* [ ] Deployment
* [ ] DevOps
* [ ] Code Craft
* [x] Workflow/Tools
* [ ] Show Type or Series
* [ ] Something Else

## (REQUIRED) How are you affiliated with Coding Garden?

Please check all that apply

* [x] [YouTube Subscriber](https://www.youtube.com/codinggardenwithcj?sub_confirmation=1)
* [ ] [Patron](https://www.patreon.com/CodingGardenWithCJ)
* [ ] [Donor](https://streamlabs.com/CodingGardenWithCJ)

## (REQUIRED) Describe your suggestion
Could you update the landscaping template to include Twitch Subscribers, please?

## (Optional) Related Links or Resources
* https://github.com/CodingGarden/landscaping/blob/master/.github/ISSUE_TEMPLATE/topic-suggestion.md#required-how-are-you-affiliated-with-coding-garden

**Comment by w3cj** [comment]
Done.
